# Generated by Django 3.2.3 on 2021-07-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20)),
                ('likes', models.IntegerField()),
                ('tags', models.CharField(max_length=200)),
                ('post_type', models.CharField(choices=[('text', 'Text'), ('link', 'Link'), ('images', 'Images')], default='text', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=1000)),
                ('text2', models.CharField(max_length=2000)),
                ('type', models.CharField(choices=[('Blog', 'Blog'), ('Quote', 'Quote')], max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TumblrApp.post')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('caption', models.CharField(max_length=2000)),
                ('type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Github', 'Github'), ('Bookmark', 'Bookmark')], max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TumblrApp.post')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TumblrApp.post')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TumblrApp.post')),
            ],
        ),
    ]
