# Generated by Django 3.2.3 on 2021-07-14 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TumblrApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
